version: "3.8"
services:
  nginx:
    image: devsecops83/nginx-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./certs
        target: /etc/nginx/certs/
      - type: bind
        source: ./sites
        target: /etc/nginx/sites/
